config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :members
  resource :registrations, :only => [:create, :edit, :new]
  resource :accounts, :only => [:show]
  resources :institutions, :only => [:index]

  root  'static_pages#home' 
end

app/models/institution.rb
class Institution < ApplicationRecord
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @institutions = get_institutions
  end

private

  def get_institutions
    institution_response = client.institutions.list_institutions()
    institution_response&.institutions
  rescue Atrium::ApiError => e
    Rails.logger.info "Exception when calling InstitutionsApi->list_institutions: #{e}"
  end 
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_institution.html.erb
  <tr class="institution is-dark-gray">
  <td>
    <img class="column insitution-image" src='<%=institution.small_logo_url %>'>
  </td>
  <td>
      <%= link_to "#{institution.name}",{
        :controller => "members",
        :action => "new",
        :method => "get",
        :institution_code => institution.code
      }, class: "has-text-white button institution-button is-medium-gray is-fullwidth" %>
    </td>
  </tr>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<section class="section">
    <div class="container">
            <div class="table-container box is-transparent"> 
                    <table class="table institutions-table">
                        <%= render partial: 'institution', collection: @institutions %>
                    </table>
                </div>
            </div>
        </div>
</section>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @institution.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>