config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :members
  resource :registrations, :only => [:create, :edit, :new]
  resource :accounts, :only => [:show]
  resources :institutions, :only => [:index]

  root  'static_pages#home' 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to members_path
    end 
  end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="box is-light-gray top-margin-small is-half-width is-centered">
    <figure class="is-centered">
      <img src=<%= asset_url("finlogo.png") %> id="logo" class="is-half-width" />
    </figure>
    <%= form_for(:user, :url => session_path(:user)) do |f| %>
      <div class="field">
        <%= f.label "Email", class: "label has-text-white" %>
        <%= f.text_field :email, class: 'input is-primary is-rounded'%>
      </div>
      <div class="field">
        <%= f.label "Password", class: "label has-text-white" %>
        <%= f.password_field :password, class: 'input is-primary is-rounded' %>
      </div>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me, class: "label has-text-white" %>
      <%= f.submit 'Sign in', class: 'button is-dark-gray has-text-white' %>
      <div class="field">
        <%= link_to "Forgot your password?", new_password_path(:user), class: 'has-text-white' %>
      </div>
    <% end %>
  </div>
</div>