config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :members
  resource :registrations, :only => [:create, :edit, :new]
  resource :accounts, :only => [:show]
  resources :institutions, :only => [:index]

  root  'static_pages#home' 
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user

  def self.from_atrium_member(atrium_member, user_id)
    Member.new(
      :guid => atrium_member.guid, 
      :user_guid => atrium_member.user_guid, 
      :institution_code => atrium_member.institution_code, 
      :user_id => user_id
      )
  end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < ApplicationController
  def new
    @member_id = registration_params[:id]
    @member_guid = get_member_guid(@member_id)
    @challenges = list_challenges(@member_guid)
  end 

  def create 
    challenges = credentials_to_array(registration_params[:challenges].to_h)
    resume_aggregation(registration_params[:member_guid], challenges)
    poll_member_status(registration_params[:member_guid], registration_params[:id])
  end 

  def edit
    member_guid = get_member_guid(registration_params[:id])
    member_status = read_member_status(member_guid)
    handle_connection_status(member_status, member_guid, registration_params[:id])
  end 

private

  def bad_credentials_status(member_id)
    redirect_to edit_member_path(:id => member_id)
  end 

  def challenged_status(member_id)
    redirect_to registrations_new_path(:id => member_id)
  end 
  
  def clean_status(status)
    redirect_to members_path
  end 

  def display_message_status(member_id)
    redirect_to member_path(member_id)
  end   

  def handle_connection_status(member_status, member_guid, member_id)
    connection_status = member_status.connection_status
    case connection_status
    when "CONNECTED"
      clean_status(connection_status)
    when "CHALLENGED"
      challenged_status(member_id)
    when "EXPIRED", "RECONNECTED", "RESUMED", "CREATED"
      reaggregate_status(connection_status, member_guid, member_id)
    when "IMPORTED", "DENIED", "PREVENTED", "FAILED"
      bad_credentials_status(member_id)
    else 
      display_message_status(member_id)
    end
  end 

  def list_challenges(member_guid)
    challenges_response = client.members.list_member_mfa_challenges(member_guid, current_user.guid)
    challenges_response&.challenges
  rescue Atrium::ApiError => e
    Rails.logger.info "Exception when calling MembersApi->list_member_mfa_challenges: #{e}"
  end 

  def poll_member_status(member_guid, member_id)
    member_status = read_member_status(member_guid)
    loop do 
      sleep(1)
      member_status = read_member_status(member_guid)
      break unless member_status.connection_status == "CREATED" || member_status.connection_status == "RESUMED"
    end 
    handle_connection_status(member_status, member_guid, member_id)
  end   

  def registration_params
    params.permit(:member_guid, :id, :authenticity_token, :commit, :challenge_questions => [], :challenges => {})
  end 

  def reaggregate_status(status, member_guid, member_id)
    aggregate_member(member_guid)
    poll_member_status(member_guid, member_id)
  end

  def resume_aggregation(member_guid, challenges)
    member_info = {:member => {:challenges => challenges}}
    body = Atrium::MemberResumeRequestBody.new(member_info)
    resume_aggregation_response = client.members.resume_member(member_guid, current_user.guid, body)
  rescue Atrium::ApiError => e
    Rails.logger.info "Exception when calling MembersApi->resume_member: #{e}"
  end 
end 

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!

  def create
    member_credentials = credentials_to_array(member_params[:credentials].to_h)
    atrium_member = create_atrium_member(member_params[:institution_code], member_credentials)
    member = Member.from_atrium_member(atrium_member, current_user.id)
    if member.save!
      redirect_to edit_registrations_path(:id => member.id)
    else  
      redirect_to '/institutions'
    end         
  end 

  def destroy
    delete_member(member_guid)
    @member = Member.find(member_params[:id])
    @member.destroy
    redirect_to members_path
  end

  def edit
    member_status = read_member_status(member_guid)
    @connection_status = ConnectionStatus.find_by_name(member_status.connection_status)
    @institution_credentials = list_member_credentials(member_guid)
    @form_url = "/members/#{member_params[:id]}"
    @method = :patch
  end

  def index 
    @members ||= members_body(current_user.members.all)
  end 

  def new 
    @institution_code = member_params[:institution_code]
    @institution_credentials = get_institution_credentials(@institution_code)
    @form_url = '/members'
  end 

  def show
    @member = Member.find(member_params[:id])
    member_status = read_member_status(@member.guid)
    @connection_status = ConnectionStatus.find_by_name(member_status.connection_status)
    @institution = read_institution(@member.institution_code)
    @accounts = accounts_body(@member.guid)
  end 

  def update
    updated_credentials = credentials_to_array(member_params[:credentials].to_h)
    update_member_credentials(member_guid, updated_credentials)
    aggregate_member(member_guid)
    redirect_to members_path
  end
  
private 

  def accounts_body(member_guid)
    accounts = get_member_accounts(member_guid)
    accounts.map do |account|
      {
        :guid => account.guid,
        :name => account.name,
        :balance => account.balance
      }
    end 
  end 

  def create_atrium_member(institution_code, credentials)
    member_info = {:member => {:institution_code => institution_code, :credentials => credentials, :skip_aggregation => false}}
    body = Atrium::MemberCreateRequestBody.new(member_info)
    member_response = client.members.create_member(current_user.guid, body)
    member_response&.member
  rescue Atrium::ApiError => e
    Rails.logger.info "Exception when calling MembersApi->create_member: #{e}"
  end 

  def delete_member(member_guid)
    client.members.delete_member(member_guid, current_user.guid)
  rescue Atrium::ApiError => e
    Rails.logger.info "Exception when calling MembersApi->delete_member: #{e}"
  end

  def get_institution_credentials(institution_code)
    institution_credentials_response = client.institutions.read_institution_credentials(institution_code)
    institution_credentials_response&.credentials
rescue Atrium::ApiError => e
    Rails.logger.info "Exception when calling InstitutionsApi->read_institution_credentials: #{e}"
end

  def list_member_credentials(member_guid)
    credentials_response = client.members.list_member_credentials(member_guid, current_user.guid)
    credentials_response&.credentials
  rescue Atrium::ApiError => e
    Rails.logger.info "Exception when calling MembersApi->list_member_credentials: #{e}"
  end

  def members_body(members)
    members.map do |member|
      member_status = read_member_status(member.guid)
      institution = read_institution(member.institution_code)
      accounts = accounts_body(member.guid)
      { :member => {
        :member_guid => member.guid,
        :id => member.id,
        :institution_name => institution.name,
        :institution_logo => institution.small_logo_url,
        :connection_status => member_status.connection_status,
        :accounts => accounts
        }
      }
    end
  end

  def member_guid
    get_member_guid(member_params[:id])
  end 

  def member_params
    params.permit(:member_guid, :institution_code, :id, :authenticity_token, :commit, :_method, :institution_name, :institution_logo, credentials: {})
  end 

  def update_member_credentials(member_guid, credentials)
    member_body = {:member => {:credentials => credentials}}
    opts = {body: Atrium::MemberUpdateRequestBody.new(member_body)}
    update_credentials_response = client.members.update_member(member_guid, current_user.guid, opts)
  rescue Atrium::ApiError => e
    Rails.logger.info "Exception when calling MembersApi->update_member: #{e}"
  end
end 

app/helpers/members/registrations_helper.rb
module Members::RegistrationsHelper
  def mfa_image(challenge)
    image_tag "#{challenge.image_data}" if challenge.type == "IMAGE_DATA" 
  end

  def mfa_type(challenge, f)
    if challenge.type == "TEXT" || challenge.type == "IMAGE_DATA"
      render partial: "input_mfa", locals: { f: f, challenge: challenge }
    end 
  end 
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_account.html.erb
<tr>
	<td>
		<%= link_to "#{account[:name]} -  $#{account[:balance]}", accounts_path(:account_guid => account[:guid]),
		 class: "button account-button is-fullwidth is-dark-gray has-text-white" %>
    </td>
</tr>

app/views/members/_credential_form.html.erb
<div class="container">
    <div class="box is-dark-gray is-half-width is-centered top-margin-small">
        <%=form_with url: @form_url, method: @method ||= :post do |f| %>
            <%= render partial: 'institution_credential', collection: @institution_credentials, locals: {f:f} %>
            <%= f.hidden_field 'institution_code', :value => @institution_code %>
            <%= f.submit "Submit", class:"button is-dark-gray has-text-white" %>
        <% end %>
    </div>
</div>

app/views/members/_delete_button.html.erb
<%= link_to "Delete Member",
 member_path(@member), 
 data: {:confirm => 'Are you sure?'},
 :method => "delete",
  class: "button is-dark-gray has-text-white" 
%>

app/views/members/_institution_credential.erb
<div class="field">
  <%= f.label institution_credential.label, class: "label has-text-white" %>
  <% if institution_credential.type == "PASSWORD" %>
    <%= f.password_field "credentials[#{institution_credential.guid}]", class: "input is-rounded is-primary" %>
  <% else %>
    <%= f.text_field "credentials[#{institution_credential.guid}]", class: "input is-rounded is-primary" %>
  <% end %>
</div>

app/views/members/_member.html.erb
<div class="box is-dark-gray member-box">
  <div class="card is-dark-gray no-shadow">
    <% member = member[:member] %>
    <div class="card-content member-card">
      <div class="media box is-dark-gray">
        <div class="media-left">
            <figure class="image is-48x48">
                <img src=<%= member[:institution_logo]%> />
            </figure>
        </div>
        <div class="media-content">
            <p class="title is-4 has-text-white"><%= member[:institution_name] %></p>
        </div>
      </div>
      <div class="box is-medium-gray">
        <%= link_to "View Membership", member_path(:id => member[:id]), class: "button is-fullwidth member-control-button has-text-white"  %>  
        <% unless member[:connection_status] == "CONNECTED" %>
          <%= link_to "Resolve Issues", edit_registrations_path(id: member[:id]), class: "button is-fullwidth member-control-button resolve-issue" %>
        <% end %>
      </div>
      <div class="box is-medium-gray"> 
        <table class="borderless-table">
          <tbody class="accounts-body">
            <%= render partial: 'account', collection: member[:accounts] %>   
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/members/edit.html.erb
<div class="container top-container">
  <div class="box member-box is-dark-gray top-margin-small">
    <p class="subtitle is-4 has-text-danger"><%= @connection_status.message %></p>
    <%= render partial: 'credential_form' %>
  </div>
</div>

app/views/members/index.html.erb
<div class="section">
    <div class="level" id="add-membership">
        <div class="title level-item has-centered has-text-white">Accounts</div>
        <%= link_to "Add another account",{
            :controller => "institutions",
            :action => "index",
            :method => "get",
        }, class: "button level-item is-dark-gray has-centered has-text-white" %>
    </div>
</div>
<div class="section">
    <%= render partial: 'member', collection: @members %>
    <div>
    </div>
</div> 

app/views/members/new.html.erb
<div class="container">
    <%= current_user.guid %>
    <div>
        <%=form_with url: '/members' do |f| %>
            <%= render partial: 'institution_credential', collection: @institution_credentials, locals: {f:f} %>
            <%= f.hidden_field 'institution_code', :value => @institution_code %>
            <%= f.submit "create member" %>
        <% end %>
    </div>
</div>

app/views/members/show.html.erb
<div class="section>"
  <div class="container">
    <div class="box member-box is-dark-gray top-margin-small">
      <div class='card is-dark-gray'>
        <%= @member_guid %>
        <% unless @connection_status.name == "CONNECTED" %>
          <p class="title is-4 has-text-white"><%= @connection_status.name %></p>
          <p class="subtitle is-6 has-text-white"><%= @connection_status.message %></p>
          <%= link_to "Resolve Issues", edit_registrations_path(id: @member.id), class: "button is-fullwidth member-control-button resolve-issue" %>
          <%= render 'delete_button' %>
        <% else %>
          <div class="media">
            <div class="media-left">
              <figure class="image is-96x96">
                <img src=<%= @institution.medium_logo_url %> />
              </figure>
            </div>
            <div class="media-content">
              <p class ="subtitle is-4 has-text-white">Your Membership at:</p>
              <p class="title is-1 has-text-white"><%= @institution.name %></p>
              <%= render 'delete_button' %>
            </div>
          </div>
          <div class="content">
            <div class="box is-medium-gray">
              <table class="borderless-table">
                <tbody class="accounts-body">
                  <%= render partial: 'account', collection: @accounts %>
                </tbody>
              </table>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>